# Generated by Django 2.2.4 on 2021-07-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210726_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='male', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cutomer',
            field=models.ManyToManyField(null=True, to='backend.Customer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Salary'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Street'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(null=True, to='backend.Supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
