# Generated by Django 2.2.4 on 2021-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210726_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cutomer',
            field=models.ManyToManyField(to='backend.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(to='backend.Supplier'),
        ),
    ]
