# Generated by Django 2.2.4 on 2021-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210726_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='job_id',
            new_name='service_id',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
