# Generated by Django 2.2.4 on 2021-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210726_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
