# Generated by Django 2.2.4 on 2021-07-26 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210726_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_credit', models.BooleanField(help_text='When positive the amount given is paid by the client')),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True, max_length=150, null=True)),
                ('payment_method', models.CharField(choices=[('om', 'Orange Money'), ('momo', 'MTN Money')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Customer')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ServiceLookup')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Service')),
            ],
        ),
    ]
