# Generated by Django 2.2.4 on 2021-07-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210726_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceline',
            name='name',
        ),
        migrations.RemoveField(
            model_name='serviceline',
            name='service_id',
        ),
        migrations.AddField(
            model_name='serviceline',
            name='lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup', to='backend.ServiceLookup'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='backend.Service'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Service'),
        ),
    ]
