# Generated by Django 2.2.4 on 2021-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210726_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceline',
            name='product_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
