# Generated by Django 2.2.4 on 2021-07-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_serviceline_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceline',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='serviceline',
            name='product_quantity',
        ),
    ]
