# Generated by Django 2.2.4 on 2021-07-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210726_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='department_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Department'),
        ),
        migrations.AddField(
            model_name='service',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Employee'),
            preserve_default=False,
        ),
    ]
