# Generated by Django 2.2.4 on 2021-08-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210726_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Salary'),
        ),
        migrations.AlterField(
            model_name='serviceline',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicelines', to='backend.Service'),
        ),
    ]
