# Generated by Django 2.2.4 on 2021-08-24 16:45

import descriptive_id.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210820_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', descriptive_id.fields.DescriptiveIDField(auto=True, max_length=20, prefix='SALE_')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True, max_length=150, null=True)),
                ('payment_method', models.CharField(choices=[('om', 'Orange Money'), ('momo', 'MTN Money')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicelines', to='backend.Sale')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Product')),
            ],
        ),
    ]
