# Generated by Django 2.2.4 on 2021-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210830_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceline',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
