# Generated by Django 2.2.4 on 2021-08-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_serviceline_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceline',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
